eureka:
  client:
    service-url:
      defaultZone: http://192.168.43.247:8762/eureka,http://192.168.43.247:8761/eureka
spring:
  application:
    name: springcloud_ribbon_resttemplate_client
server:
  port: 9090
